# Generated by Django 4.2.2 on 2023-06-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupo',
        ),
    ]
