# Generated by Django 4.2.2 on 2023-06-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_remove_user_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='grupo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
